// Generated by CoffeeScript 1.7.1
(function() {
  var $, app, chai, jsdom;

  app = require('../app/scripts/main.coffee');

  jsdom = require("jsdom");

  $ = require("jquery")(jsdom.jsdom().createWindow());

  chai = require('chai');

  describe("A functioning system", function() {
    it("knows when to foo", function() {
      var instance;
      instance = new app;
      chai.assert.isDefined(instance);
    });
    it("should get correct value for status", function() {
      var instance;
      instance = new app;
      chai.assert.equal(instance.GetLyncPresenceString(0), 'avaliabled');
      chai.assert.equal(instance.GetLyncPresenceString(1), 'offline');
      chai.assert.equal(instance.GetLyncPresenceString(4), 'away');
      chai.assert.equal(instance.GetLyncPresenceString(6), 'busy');
      chai.assert.equal(instance.GetLyncPresenceString(9), 'donotdisturb');
      return chai.assert.equal(instance.GetLyncPresenceString(12), 'busy');
    });
  });

  it("should constrcut url based on status", function() {
    var instance, tag;
    instance = new app;
    tag = $('<li></li>');
    instance.SetImageClassStatus(tag, 2);
    chai.assert.equal($(tag).attr('class'), 'sprite-icon-status-away');
  });

}).call(this);
