// Generated by CoffeeScript 1.7.1
(function() {
  var Lync;

  Lync = (function() {
    function Lync() {}

    Lync.prototype.GetLyncPresenceString = function(status) {
      switch (status) {
        case 0:
          return "avaliabled";
        case 1:
          return "offline";
        case 2:
        case 4:
        case 16:
          return "away";
        case 3:
        case 5:
          return "incall";
        case 6:
        case 7:
        case 8:
        case 10:
          return "busy";
        case 9:
        case 15:
          return "donotdisturb";
        default:
          return "busy";
      }
    };

    Lync.prototype.SetImageClassStatus = function(liTag, status) {
      $(liTag).addClass("sprite-icon-status-" + (this.GetLyncPresenceString(status)));
    };

    return Lync;

  })();

  if (typeof module !== "") {
    module.exports = Lync;
  }

}).call(this);
